version: '3.8'

services:
  dependency-lock:
    profiles:
      - dependency-lock
    build:
      context: .
      dockerfile: dockerfiles/pip-tools.dockerfile
    volumes:
      - ./prepare-data/requirements:/prepare-data/requirements
    working_dir: /prepare-data/requirements

  prepare-data:
    profiles:
      - prepare-data
    build:
      context: .
      dockerfile: dockerfiles/prepare-data.dockerfile
    volumes:
      - ./prepare-data:/prepare-data
      - ${GAME_DIR}:/game
      - ./data:/output

  dependency-lock-recommend:
    profiles:
      - dependency-lock
    build:
      context: .
      dockerfile: dockerfiles/pip-tools.dockerfile
    volumes:
      - ./recommend/requirements:/recommend/requirements
    working_dir: /recommend/requirements

  recommend:
    build:
      context: .
      dockerfile: dockerfiles/recommend.dockerfile
    volumes:
      - ./recommend:/recommend
      - ./prepare-data/src/utils.py:/usr/local/lib/python3.11/site-packages/utils.py
      - ./data:/data
    working_dir: /recommend/src
